import pyautogui as auto

auto.sleep(2)
auto.write('cd',interval=0.05)
auto.sleep(1)
auto.press('enter')
auto.sleep(1)
auto.write('cd Desktop',interval=0.05)
auto.press('enter')
auto.sleep(1)
auto.write('mkdir helloWorld',interval=0.05)
auto.press('enter')
auto.sleep(1)
auto.write('cd helloWorld',interval=0.05)
auto.press('enter')
auto.sleep(1)
auto.write('cat > info.txt',interval=0.05)
auto.press('enter')
auto.sleep(1)
auto.write('Nombre -- Cristian',interval=0.05)
auto.sleep(1)
auto.press('enter')
auto.write('Edad -- 20',interval=0.05)
auto.sleep(1)
auto.press('enter')
auto.write('Skills -- Programming in general',interval=0.05)
auto.sleep(1)
auto.press('enter')
auto.write('Exp -- U',interval=0.05)
auto.sleep(1)
auto.press('enter')
